/**
 * Support-escalation bundle for Cloudflare tickets / platform escalations.
 * Collects EM receipts, doctor support-report, bindings matrix, and compat
 * artifacts into one attachable directory — never invents parity.
 */

import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { join, relative } from "node:path";
import { createHash } from "node:crypto";
import { artifactsDir, ensureArtifactsDir } from "../config/index.js";
import { EDGEMIRROR_VERSION } from "../version.js";
import { buildCloudflareSupportReport } from "../adapters/cloudflare/support-report.js";
import { formatBindingsSupportTable } from "../adapters/cloudflare/bindings.js";
import { detectCloudflareAuth } from "../adapters/cloudflare/auth.js";

export interface EscalationManifest {
  schemaVersion: "1.0";
  kind: "cloudflare-support-escalation";
  edgemirrorVersion: string;
  createdAt: string;
  projectRoot: string;
  purpose: string;
  authenticity: string[];
  files: Array<{ path: string; sha256: string; bytes: number }>;
  findingIds: string[];
  authMode: string;
  remoteConfigured: boolean;
}

function sha256(buf: Buffer | string): string {
  return createHash("sha256").update(buf).digest("hex");
}

function collectFiles(dir: string): string[] {
  if (!existsSync(dir)) return [];
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...collectFiles(full));
    else if (entry.isFile()) out.push(full);
  }
  return out;
}

function listFindingIds(rootArtifacts: string): string[] {
  const ids = new Set<string>();
  const receiptDirs = [
    join(rootArtifacts, "receipts"),
    ...listRunDirs(rootArtifacts).map((r) => join(r, "receipts")),
  ];
  for (const dir of receiptDirs) {
    if (!existsSync(dir)) continue;
    for (const name of readdirSync(dir)) {
      const m = /^(EM-\d+)\.json$/i.exec(name);
      if (m) ids.add(m[1]!.toUpperCase());
    }
  }
  return [...ids].sort();
}

function listRunDirs(root: string): string[] {
  const runs = join(root, "runs");
  if (!existsSync(runs)) return [];
  return readdirSync(runs, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => join(runs, d.name));
}

function writeTicketGuide(bundleDir: string, findingIds: string[]): void {
  const guide = `# Cloudflare support escalation packet

Generated by \`edgemirror support-bundle\` (EdgeMirror ${EDGEMIRROR_VERSION}).

EdgeMirror is an **independent** source-available proprietary project and is
**not affiliated with, endorsed by, or sponsored by Cloudflare, Inc.**
Attach this directory
(or a zip of it) to a Cloudflare support / platform ticket when escalating a
Workers local ↔ production parity issue.

## What to attach

1. This entire folder (preferred), or zip it.
2. Your minimal Worker repro + \`wrangler.toml\` / \`wrangler.json(c)\` if not already in the ticket.
3. Compatibility date(s) under investigation.

## How to read the evidence

| File | Purpose |
|------|---------|
| \`support-report.json\` | Machine-readable EdgeMirror Cloudflare capability + honesty contract |
| \`bindings-matrix.txt\` | STABLE bindings parity capability table |
| \`doctor-fingerprint.json\` | Wrangler/workerd/auth fingerprint (no secrets) |
| \`COMPAT.md\` / \`compat/\` | Compatibility-date matrix cells (only real local runs) |
| \`receipts/EM-###.json\` | Differential evidence receipts |
| \`runs/\` | Traces / reports from verify runs |
| \`manifest.json\` | Integrity list (SHA-256) |

Finding IDs in this bundle: ${findingIds.length ? findingIds.join(", ") : "(none yet — run \`edgemirror verify\` first)"}

## Honest caveats (do not skip)

- Missing Cloudflare credentials → \`REMOTE_NOT_CONFIGURED\`. That is **not** a MATCH.
- DEMO / pitch-demo findings are labeled and must not be cited as production bugs.
- Infrastructure / auth failures are not \`RUNTIME_DIVERGENCE\`.
- EdgeMirror capability levels describe **EdgeMirror**, not Cloudflare product GA.

## Suggested ticket summary template

\`\`\`
Title: Workers local vs production divergence (EdgeMirror EM-###)

Summary:
- Local: wrangler dev --local (workerd)
- Remote/preview: <workers.dev | preview URL | REMOTE_NOT_CONFIGURED>
- Compatibility date: <YYYY-MM-DD>
- Finding ID(s): <EM-###>
- Classification: <MATCH | RUNTIME_DIVERGENCE | …>
- Attach: EdgeMirror support-bundle (manifest.json + receipts)

Repro:
1. …
2. npx edgemirror verify --format agent
3. npx edgemirror support-bundle
\`\`\`
`;
  writeFileSync(join(bundleDir, "CLOUDFLARE_TICKET.md"), guide, "utf8");
}

/**
 * Build a support-escalation directory under `.edgemirror/support-bundles/`.
 */
export function createSupportEscalationBundle(input: {
  projectRoot: string;
  doctorFingerprint?: unknown;
}): { bundleDir: string; manifest: EscalationManifest } {
  const projectRoot = input.projectRoot;
  ensureArtifactsDir(projectRoot);
  const artifacts = artifactsDir(projectRoot);
  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  const bundleDir = join(artifacts, "support-bundles", `cf-escalation-${stamp}`);
  mkdirSync(bundleDir, { recursive: true });

  const auth = detectCloudflareAuth();
  const findingIds = listFindingIds(artifacts);

  // Core machine-readable reports
  writeFileSync(
    join(bundleDir, "support-report.json"),
    JSON.stringify(buildCloudflareSupportReport(), null, 2),
    "utf8",
  );
  writeFileSync(
    join(bundleDir, "bindings-matrix.txt"),
    formatBindingsSupportTable() + "\n",
    "utf8",
  );

  if (input.doctorFingerprint !== undefined) {
    writeFileSync(
      join(bundleDir, "doctor-fingerprint.json"),
      JSON.stringify(input.doctorFingerprint, null, 2),
      "utf8",
    );
  }

  // Copy receipts
  const receiptsOut = join(bundleDir, "receipts");
  mkdirSync(receiptsOut, { recursive: true });
  for (const id of findingIds) {
    const candidates = [
      join(artifacts, "receipts", `${id}.json`),
      ...listRunDirs(artifacts).map((r) => join(r, "receipts", `${id}.json`)),
    ];
    for (const src of candidates) {
      if (existsSync(src)) {
        copyFileSync(src, join(receiptsOut, `${id}.json`));
        break;
      }
    }
  }

  // Copy recent run artifacts (bounded)
  const runsOut = join(bundleDir, "runs");
  const runDirs = listRunDirs(artifacts).slice(-5);
  for (const run of runDirs) {
    const name = run.split(/[/\\]/).pop()!;
    const destRun = join(runsOut, name);
    for (const f of collectFiles(run)) {
      const rel = relative(run, f);
      const dest = join(destRun, rel);
      mkdirSync(join(dest, ".."), { recursive: true });
      copyFileSync(f, dest);
    }
  }

  // Compat / matrix artifacts if present
  const compatCandidates = [
    join(artifacts, "compat"),
    join(artifacts, "matrix"),
    join(projectRoot, ".edgemirror", "compat"),
  ];
  for (const c of compatCandidates) {
    if (!existsSync(c)) continue;
    const destCompat = join(bundleDir, "compat");
    for (const f of collectFiles(c)) {
      const rel = relative(c, f);
      const dest = join(destCompat, rel);
      mkdirSync(join(dest, ".."), { recursive: true });
      copyFileSync(f, dest);
    }
  }

  writeTicketGuide(bundleDir, findingIds);

  const allFiles = collectFiles(bundleDir).filter(
    (f) => !f.endsWith("manifest.json"),
  );
  const files = allFiles.map((full) => {
    const buf = readFileSync(full);
    return {
      path: relative(bundleDir, full).replace(/\\/g, "/"),
      sha256: sha256(buf),
      bytes: buf.byteLength,
    };
  });

  const manifest: EscalationManifest = {
    schemaVersion: "1.0",
    kind: "cloudflare-support-escalation",
    edgemirrorVersion: EDGEMIRROR_VERSION,
    createdAt: new Date().toISOString(),
    projectRoot,
    purpose:
      "Attach to Cloudflare support / platform tickets for Workers local↔prod differential evidence",
    authenticity: [
      "Never invents remote traces; REMOTE_NOT_CONFIGURED when unconfigured",
      "DEMO findings must remain labeled",
      "Not affiliated with Cloudflare, Inc.",
    ],
    files,
    findingIds,
    authMode: auth.mode,
    remoteConfigured: auth.configured,
  };

  writeFileSync(
    join(bundleDir, "manifest.json"),
    JSON.stringify(manifest, null, 2),
    "utf8",
  );

  return { bundleDir, manifest };
}
